# Generated by Django 3.0.1 on 2020-07-15 08:27

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='ad_type',
            field=models.CharField(choices=[('education', 'education'), ('electronics', 'electronics'), ('garments', 'garments'), ('textile', 'textile'), ('bollywood', 'bollywood')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='pay_status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='ad_type',
            field=models.CharField(choices=[('education', 'education'), ('electronics', 'electronics'), ('garments', 'garments'), ('textile', 'textile'), ('bollywood', 'bollywood')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='to_date',
            field=models.DateField(default=datetime.date(2020, 7, 15), null=True),
        ),
        migrations.AlterField(
            model_name='order_banner',
            name='status',
            field=models.CharField(default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=75, size=[25, 25], upload_to='logo/'),
        ),
    ]
